Repository nari-labs/dia, pull requests merged in 2025-04, with the labels that each got.

#45 Update layers.py - Error Float16 key.dtype: float and value.dtype: float instead
  dia/layers.py
Labels: bug

#63 docs: fix blank typo in README.md
  README.md
Labels: documentation

#81 docs: adjust VRAM requirements 10GB to 12-13GB
  README.md
Labels: documentation

#46 Create Dockerfile - Feature adding ability for users to run Dia with docker container
  Dockerfile.cpu
  Dockerfile.gpu
  app.py
Labels: enhancement

#94 docs: apply -f parameter for docker build command
  docker/Dockerfile.cpu
  docker/Dockerfile.gpu
Labels: documentation

#56 Improve Hugging Face integration (safetensors)
  dia/layers.py
  dia/model.py
Labels: enhancement
